development:
  adapter: postgresql
  encoding: unicode
  database: trellino_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: trellino_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: trellino_production
  pool: 5
  username: 
  password:
